#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Shogo Uchida
import sys
　   #スライドの関係で1行だけど、本来、関数の前後は2行空白をあける                
def tonum(s):   #def 関数の名前(引数)で関数を定義
    try:
        return int(s)
    except:
        return float(s)
　 
ans = 0
for line in sys.stdin:
        ans += tonum(line)
　 
print(ans)
